version: '2.2'
services:
  openhab:
    # https://github.com/openhab/openhab-docker
    image: "openhab/openhab:3.0.0"
    restart: always
    ports:
      - "8080:8080"
    devices:
      # Config for the GoControl Z-Wave/Zigbee HUSBZB-1 USB Hub
      # https://amzn.to/3i29311
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=America/Los_Angeles"
